spring.application.name=PRISM

# Server
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:<YOUR DB>
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=<USERNAME>
spring.datasource.password=<PASSWORD>
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Email Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=<YOUR MAIL>
spring.mail.password=<YOUR MAILL PASSWORD>
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Twilio Settings
twilio.account.sid=<TWILIO SID>
twilio.auth.token=<TWILIO AUTH TOKEN>
twilio.phone.number=<TWILIO PHONE NO>
emergency.contact.number=<TWILIO CONTACT NO>

#Gemini
gemini.api.key=<GEMINI API KEY>
